name: 'Add Milestone By Due Date'
description: 'Adds the current or farthest due milestone to pull requests and issues'
author: 'Ben Elan'
branding:
  icon: git-branch
  color: green
inputs:
  repo-token:
    description: 'Token for the repository. Defaults to `{{ github.token }}`'
    default: ${{ github.token }}
    required: false
  farthest:
    description: 'Set this boolean to `true` if you want to add the milestone with the farthest due date. Defaults to `false` which adds the current milestone.'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
