name: 'Add Milestone By Due Date'
description: 'Adds the current or farthest due milestone to pull requests and issues'
author: 'Ben Elan'
branding:
  icon: git-branch
  color: green
inputs:
  github_token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  farthest:
    description: 'Set this boolean to `true` if you want to add the milestone with the farthest due date. Defaults to `false` which adds the current milestone.'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
