name: 'Add Current Milestone'
on:
  issues:
    types: [opened]
    branches: [ master ]
  pull_request:
    types: [opened]
    branches: [ master ]
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
